version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432"
  web:
    stdin_open: true
    tty: true
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
