default: &default
 adapter: postgresql
 encoding: unicode
 host: db
 username: postgres
 password: mypassword
 pool: 5
development:
 <<: *default
 database: obras_bibliograficas_development
test:
 <<: *default
 database: obras_bibliograficas_test